# -------------------------
# Jekyll Configuration File
# -------------------------

# Site settings
title: Wessex Skies

description:
  Somewhere to keep my notes. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wessex-skies.github.io"

# Build Settings
plugins:
  - jekyll-feed
  - jekyll-paginate 
  - jekyll-sitemap 
  - jekyll-include-cache 

permalink: /:year/:month/:day/:title/

include: ['_pages']

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ----------------------
# Theme Minimal Mistakes 
#
# Documentation on this theme can be found at 
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/
#
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
#minimal_mistakes_skin: "mint" 
# "air", "aqua", "contrast", "default", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale: "en-GB" 
date_format: "%d %B %Y"
enable_copy_code_button: true

# Search 
search: true
lunr:
  search_within_pages: true 

# Defaults 
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      layout: single
      comments: false
      share: false
      related: false
      author_profile: false
    
# Author 
# For this to appear on the web site, `author_profile` must be set to `true`
author:
  name     : "Paul"
  avatar   : #"/assets/images/bio-photo.jpg"
  bio      : "More to follow"
  location : "Under the Wessex Skies"

# End of theme settings
# ----------------------

